- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    my_host: coredns
    my_domain: "{{ my_host }}.labs.local"
    my_ipaddr: "{{ ansible_facts.enp0s9.ipv4.address }}"
    my_data: /coredns
    disk_sdc: "{{ my_data }}"
  #
  roles:
    - docker
    - vdisks
    - coredns
    - ca    
    - nginx

  tasks:
    - debug: msg="{{ ansible_facts }}"
        

