- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    my_host: coredns
    my_domain: "{{ my_host }}.labs.local"
    my_ipaddr: "{{ ansible_facts.enp0s9.ipv4.address }}"
    my_dns_data: /coredns
    disk_sdc: "{{ my_dns_data }}"
    my_ca_data: /ca
    disk_sdd: "{{ my_ca_data }}"
    coredns_ver: 1.7.0
    my_ldap_data: /ldap
    disk_sde: "{{ my_ldap_data }}"
  #
  roles:
    - vdisks
    - coredns
    - ca
    - nginx
    #- ldap
    - ldap2


        

