- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    my_host: coredns
    # メール・ドメイン
    mail_domain: "labo.local"
    # サーバー・ドメイン
    my_domain: "{{ my_host }}.labs.local"
    fqdn:      "ca.labo.local"
    my_ipaddr: "{{ ansible_facts.enp0s9.ipv4.address }}"
    ca_ip:     "127.0.0.1"
    my_dns_data: /coredns
    disk_sdc: "{{ my_dns_data }}"
    my_ca_data: /ca
    disk_sdd: "{{ my_ca_data }}"
    coredns_ver: 1.7.0
    my_ldap_data: /ldap
    disk_sde: "{{ my_ldap_data }}"
    admin_user: ubuntu
  #
  roles:
    - vdisks
    - coredns
    - ca
    - nginx
    - ldap2
    - docker
    - mail-client
        

