- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk1 }}"

- name: Create mount point
  file:
    path: "{{ disk_sdc }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk1 }}
  mount:
    path: "{{ disk_sdc }}"
    src:  "{{ disk1 }}"
    fstype: ext4
    state: mounted

- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk2 }}"

- name: Create mount point
  file:
    path: "{{ disk_sdd }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk2 }}
  mount:
    path: "{{ disk_sdd }}"
    src:  "{{ disk2 }}"
    fstype: ext4
    state: mounted
    
