# Master と Workerで共通のタスク
#- debug: msg="{{ ansible_facts }}"

##  Docker のインストール
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nginx

- name: ca web page config
  template:
    src: ca.conf
    dest: /etc/nginx/conf.d/ca.conf
    owner: root
    group: root
    mode: '0644'

- name: Re-Start Nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
    
