- name: Configure CA
  shell: |
    cp -r /vagrant/ca_bin/*  {{ my_ca_data }}
  args:
    chdir: "{{ my_ca_data }}"

- shell: |
    ./setup_ca.sh
    ./issue_certs.sh
  args:
      chdir: "{{ my_ca_data }}"
