- name: copy ca files create_csr.sh
  copy:
    src: create_csr.sh
    dest: "{{ my_ca_data }}"
    owner: root
    group: root
    mode: '0755'

- name: copy ca files environment
  copy:
    src: environment
    dest: "{{ my_ca_data }}"
    owner: root
    group: root
    mode: '0644'
    
- name: copy ca files issue_certs.sh
  copy:
    src: issue_certs.sh
    dest: "{{ my_ca_data }}"
    owner: root
    group: root
    mode: '0755'

- name: copy ca files setup_ca.sh
  copy:
    src: setup_ca.sh
    dest: "{{ my_ca_data }}"    
    owner: root
    group: root
    mode: '0755'

- name: copy ca files signature_cert.sh
  copy:
    src: signature_cert.sh
    dest: "{{ my_ca_data }}"        
    owner: root
    group: root
    mode: '0755'

- name: copy ca files cp_ca_htdocs.sh
  copy:
    src: cp_ca_htdocs.sh
    dest: "{{ my_ca_data }}"    
    owner: root
    group: root
    mode: '0755'


- shell: |
    ./setup_ca.sh
    ./issue_certs.sh
    #./cp_ca_htdocs.sh
  args:
      chdir: "{{ my_ca_data }}"
