- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    #update_cache: yes
  vars:
    packages:
    - curl

- name: Downloading CoreDNS
  stat:
    path: /usr/local/bin/coredns
  register: file_coredns_tgz

- get_url:
    url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_ver }}/coredns_{{ coredns_ver }}_linux_amd64.tgz"
    dest: /tmp
    mode: '0755'
  when: file_coredns_tgz.stat.exists == false

- name: Install coredns 
  unarchive:
    src: "/tmp/coredns_{{ coredns_ver }}_linux_amd64.tgz"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
  
- name: copy coredns.service
  template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: root
    mode: '0644'

- name: copy Corefile
  template:
    src: Corefile
    dest: /coredns/Corefile
    owner: root
    group: root
    mode: '0644'

- name: copy zone file labs.db
  template:
    src: labs.db
    dest: /coredns/labs.db
    owner: root
    group: root
    mode: '0644'

    
- name: Stop dns proxy
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: set resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Start Coredns deamons
  systemd:
    name: coredns
    state: started
    daemon_reload: yes
    enabled: yes

