- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - build-essential
    - autoconf
    - libdb5.3-dev 
    - php
    - php-ldap
    - php-xml
    - php-fpm
    #- slapd
    #- ldap-utils


- name: Download OpenLdap
  get_url:
    url:  https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.4.57.tgz
    dest: "{{ my_ldap_data }}"
    mode: 0440


- name: Un arcvhice OpenLdap
  unarchive:
    src:  "{{ my_ldap_data }}/openldap-2.4.57.tgz"
    dest: "{{ my_ldap_data }}"
    owner: root
    group: root
    mode: '0755'

- name: create slapd.d
  file:
    state: directory
    path: /ldap/etc/slapd.d
    owner: root
    group: root
    mode: '0755'


- name: configure 
  shell: |
      ./configure --prefix=/ldap
  args:
      chdir: "{{ my_ldap_data }}/openldap-2.4.57"


- name: make depend
  shell: |
      make depend
  args:
      chdir: "{{ my_ldap_data }}/openldap-2.4.57"


- name: make install
  shell: |
      make install
  args:
      chdir: "{{ my_ldap_data }}/openldap-2.4.57"


- name: create symbolic link
  shell: |
     ls /ldap/bin > /tmp/ldap_command_list
     while read cmd; do
       ln -s /ldap/bin/$cmd $cmd
     done </tmp/ldap_command_list
     rm /tmp/ldap_command_list
  args:
      chdir: /usr/local/bin


- name: create symbolic link
  shell: |
    /usr/local/sbin/slapadd -n 0 -F /ldap/etc/slapd.d -l /ldap/etc/openldap/slapd.ldif


- name: copy slapd.service
  template:
    src: slapd.service
    dest: /etc/systemd/system/slapd.service
    owner: root
    group: root
    mode: '0644'


- systemd:
    name:  slapd
    state: started
    daemon_reload: yes
    enabled: yes


- name: Install phpLDAPadmin
  shell: |
    NEW_PWD=secret
    PWD_HASH=$(slappasswd -s ${NEW_PWD})
    echo $PWD_HASH
  register: PWD_HASH

- name: copy ldif
  template:
    src: passwd.ldif.j2
    dest: "{{ my_ldap_data }}/passwd.ldif"
    owner: root
    group: root
    mode: 0644

- name: Install phpLDAPadmin
  shell: |
    ldapmodify -Y EXTERNAL -H ldapi:/// -f passwd.ldif
  args:
    chdir: "{{ my_ldap_data }}"


- name: Install phpLDAPadmin
  shell: |
    git clone https://github.com/breisig/phpLDAPadmin
    cd phpLDAPadmin/config
    cp config.php.example config.php
  args:
      chdir: "{{ my_ldap_data }}"

- name: change socket addr
  replace: >-
    dest='/etc/php/7.2/fpm/pool.d/www.conf'
    regexp='^listen = /run/php/php7.2-fpm.sock'
    replace='listen = 127.0.0.1:9000'

- name: restart php7.2-fpm
  systemd:
    name: php7.2-fpm
    state: restarted
    daemon_reload: yes
    enabled: yes



