- name: Re-Start dockerd
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

# 追加パッケージ導入
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - curl

- name: Configure CoreDNS Server
  shell: |
    docker pull coredns/coredns
  args:
    chdir: /coredns
      
- name: Stop dns proxy
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: set resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Configure CoreDNS Server
  shell: |
    cp -r /vagrant/coredns/* /coredns
    cp -r /vagrant/ca_bin/*  /coredns
    ./start_coredns.sh
  args:
    chdir: /coredns

